# -*- coding: utf-8 -*-
"""FileHandling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hruClZ08PUWuqCVYFtxO9u-9Wu0nVKoA

***Python File Handling***

It is imp function of any web application using it we can perform several operation like creating,updating,deleting
"""

f = open("/content/simple.txt")

f = open("/content/simple.txt",'r')
print(f.read())

f = open("/content/simple.txt",'r')
print(f.read(10))

f = open("/content/simple.txt",'r')
print(f.readline())

f = open("/content/simple.txt",'r')
print(f.readline())
print(f.readline())
print(f.readline())
print(f.readline())

f = open("/content/simple.txt",'r')
print(f.readline())
print(f.readline())
print(f.readline())
print(f.readline())
f.close()

f = open("/content/simple.txt",'a')
f.write("\n Now see new line")
f.close();
f = open("/content/simple.txt",'r')
print(f.read())

f = open("/content/simple.txt",'w')
f.write("\n Let's show new paragraph ")
f.close();
f = open("/content/simple.txt",'r')
print(f.read())

f = open("/content/simple.txt",'r')
print(f.read())

f = open("First.txt",'x')
f.close();

f = open("First.txt",'w')
f.write("This is new file")
f.close();
f=open("First.txt",'r')
print(f.read())

f = open("second.txt",'x')
f.close();

import os
os.remove("second.txt")

if os.path.exists("second.txt"):
  os.remove("second.txt")
else:
  print("file is not exists")